- id: '1698592683179'
  alias: VoiceNotifications
  description: ''
  triggers:
  - type: opened
    device_id: 27e69aa0ea80aac5fc9f89b128bb02bb
    entity_id: ee20a92f2be33c639f4a379abb36a398
    domain: binary_sensor
    trigger: device
  - type: tampered
    device_id: 27e69aa0ea80aac5fc9f89b128bb02bb
    entity_id: bb491954fab98a58d346fadf3dea869f
    domain: binary_sensor
    trigger: device
  - type: opened
    device_id: ee30e11d458110e84a0ceb230d6c3fcf
    entity_id: 4bd5a0e380f0dacbbb79badc56071f6a
    domain: binary_sensor
    trigger: device
  - type: tampered
    device_id: ee30e11d458110e84a0ceb230d6c3fcf
    entity_id: c573230ee4fc7e5f0292b6c6580ddfcf
    domain: binary_sensor
    trigger: device
  - type: tampered
    device_id: 3ff0ef6d17c887e9ea6bbf2ad15191fe
    entity_id: abecf1a83f864348d2367c75e253a5ef
    domain: binary_sensor
    trigger: device
  - type: opened
    device_id: 3ff0ef6d17c887e9ea6bbf2ad15191fe
    entity_id: 6db468c29bf0d96490a9ac2c59e9ef3a
    domain: binary_sensor
    trigger: device
  - type: turned_on
    device_id: 3e82504e7cf749250b6d82290ccad6bd
    entity_id: 90685de52680883754499da89f6376f5
    domain: switch
    trigger: device
  - type: opened
    device_id: 3fe834a8a82965a188ad5359dc6734f8
    entity_id: b59f95ad6d650d54c316e1f015f4ac82
    domain: binary_sensor
    trigger: device
  - type: opened
    device_id: 8ca5f2a5d5d73c74a5f5b7b40a2d8e89
    entity_id: 755d4f8948e4041f43aceba674c6d0c9
    domain: binary_sensor
    trigger: device
  conditions:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.voice_notifications
      state: 'on'
    - condition: state
      entity_id: alarm_control_panel.securityalarm3100
      state: disarmed
      enabled: true
  actions:
  - target:
      entity_id: media_player.speakers_group
    data:
      media_content_id: media-source://tts/reversotts?message="{{ state_attr(trigger.to_state.entity_id,
        'friendly_name') }}" {{'OPEN' if trigger.to_state.state == 'on' else 'CLOSED'}}&language=Laura-US-English
      media_content_type: provider
    metadata:
      title: 'OFF'
      thumbnail: https://brands.home-assistant.io/_/tts/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/reversotts?message=SpeechNotifications&language=Laura-US-English
    action: media_player.play_media
  mode: single
- id: '1703297345806'
  alias: Sunset
  description: ''
  triggers:
  - event: sunset
    offset: -00:01:01
    trigger: sun
  conditions: []
  actions:
  - metadata: {}
    data: {}
    target:
      device_id:
      - dd900b708c5810913edbfa2e5290ecbd
      - a4ba99b7719642420d94bebdb42e9622
      - 63d170521cffb53bef6863b6a8ecfa3c
      - 0a873709d9ade42d66bec015328266b0
      area_id: outdoor
    action: switch.turn_on
  - metadata: {}
    data:
      value: 0.5
    target:
      entity_id: input_number.speaker_volume
    action: input_number.set_value
  - if:
    - condition: and
      conditions:
      - condition: device
        device_id: 6bee91906ed371d81142b086f5dee5c4
        domain: media_player
        entity_id: e46862071587735566875d11a33ee607
        type: is_playing
    then: []
    else:
    - target:
        entity_id: media_player.speakers_group
      data:
        media_content_id: media-source://tts/reversotts?message=Good Evening Yantraa
          and Jovitha&language=Heather-US-English
        media_content_type: provider
      metadata:
        title: 'OFF'
        thumbnail: https://brands.home-assistant.io/_/tts/logo.png
        media_class: app
        children_media_class:
        navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://tts
        - media_content_type: provider
          media_content_id: media-source://tts/reversotts?message=SpeechNotifications&language=Heather-US-English
      action: media_player.play_media
    alias: Play Good evening Message
  mode: single
- id: '1703297451429'
  alias: Sunset + 3hrs
  description: ''
  triggers:
  - event: sunset
    offset: +03:00:00
    trigger: sun
    enabled: true
  - at: '21:04:00'
    trigger: time
    enabled: false
  - at: '22:03:00'
    trigger: time
  conditions:
  - condition: state
    entity_id: input_boolean.energy_saver
    state: 'on'
  actions:
  - metadata: {}
    data: {}
    target:
      device_id:
      - a4ba99b7719642420d94bebdb42e9622
      - 1d531cf53957ee6339f579fd6deaba7a
      area_id: outdoor
    action: switch.turn_off
  mode: single
- id: '1703297581987'
  alias: Midnight Schedule
  description: ''
  triggers:
  - at: '23:59:00'
    trigger: time
  - at: '23:02:00'
    trigger: time
  - at: 01:03:00
    trigger: time
  conditions:
  - condition: state
    entity_id: input_boolean.energy_saver
    state: 'on'
  actions:
  - type: turn_off
    device_id: 6db8e8b6bac1035f442a0e44b086eb33
    entity_id: 018e2d43bec65efc27548d2f9d96d97d
    domain: remote
  - metadata: {}
    data: {}
    target:
      entity_id: switch.security_switch_group
      device_id: 1d531cf53957ee6339f579fd6deaba7a
    action: switch.turn_off
  - metadata: {}
    data: {}
    target:
      entity_id: light.security_light_group
    action: light.turn_off
  - type: turn_off
    device_id: df4cf792d8865cb18aa9400b9edc7bb3
    entity_id: cd3684ef5ee45d56c934b517b3cbbcf8
    domain: switch
  mode: single
- id: '1704825676538'
  alias: Power Saving - Turn OFF Devices
  description: ''
  triggers:
  - minutes: /30
    trigger: time_pattern
  conditions:
  - condition: and
    conditions:
    - condition: sun
      before: sunset
      after: sunrise
      before_offset: -01:00:00
      after_offset: +00:30:00
    - condition: state
      entity_id: input_boolean.energy_saver
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.light_sensor_hall_illuminance
      above: 70
  actions:
  - metadata: {}
    data: {}
    target:
      entity_id: switch.security_switch_group
    action: switch.turn_off
  - metadata: {}
    data: {}
    action: light.turn_off
    target:
      entity_id: light.all_light_group
  mode: single
- id: '1705634765942'
  alias: Sunrise
  description: ''
  triggers:
  - trigger: time
    at: 06:00:00
  conditions: []
  actions:
  - metadata: {}
    data: {}
    target:
      entity_id:
      - input_boolean.energy_saver
      - input_boolean.voice_notifications
    action: input_boolean.turn_on
  - if:
    - condition: state
      entity_id: alarm_control_panel.securityalarm3100
      state: armed_night
    then:
    - metadata: {}
      data:
        value: 0.3
      target:
        entity_id: input_number.speaker_volume
      action: input_number.set_value
    - delay:
        hours: 0
        minutes: 0
        seconds: 2
        milliseconds: 0
    - action: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.securityalarm3100
      metadata: {}
      data:
        code: '5363'
    - if:
      - condition: and
        conditions:
        - condition: device
          device_id: 6bee91906ed371d81142b086f5dee5c4
          domain: media_player
          entity_id: e46862071587735566875d11a33ee607
          type: is_playing
      then: []
      else:
      - target:
          entity_id:
          - media_player.speakers_group
        data:
          media_content_type: audio/mpeg
          media_content_id: media-source://media_source/local/rooster-sound.mp3
        metadata:
          title: emergency-alarm.mp3
          thumbnail:
          media_class: music
          children_media_class:
          navigateIds:
          - {}
          - media_content_type: app
            media_content_id: media-source://media_source
        action: media_player.play_media
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - metadata: {}
    data:
      value: 0.5
    target:
      entity_id: input_number.speaker_volume
    action: input_number.set_value
  mode: single
- id: '1707608182929'
  alias: Garage and driveway light ON
  description: ''
  triggers:
  - type: opened
    device_id: 3ff0ef6d17c887e9ea6bbf2ad15191fe
    entity_id: 6db468c29bf0d96490a9ac2c59e9ef3a
    domain: binary_sensor
    trigger: device
  - type: opened
    device_id: 3fe834a8a82965a188ad5359dc6734f8
    entity_id: b59f95ad6d650d54c316e1f015f4ac82
    domain: binary_sensor
    trigger: device
  - type: opened
    device_id: 8ca5f2a5d5d73c74a5f5b7b40a2d8e89
    entity_id: 755d4f8948e4041f43aceba674c6d0c9
    domain: binary_sensor
    trigger: device
  conditions:
  - condition: time
    after: '18:00:00'
    before: 06:00:00
  actions:
  - metadata: {}
    data: {}
    target:
      device_id:
      - 57b421090ea696c870480708354d867a
      - 3d088840b274c5366c61b3417ba582cc
    action: switch.turn_on
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - if:
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.garage_one_tilt_sensor_contact
        state: 'on'
      - condition: state
        entity_id: binary_sensor.garage_tilt_senor_two_contact
        state: 'on'
      - condition: state
        entity_id: binary_sensor.0xa4c138b9ebec3506_contact
        state: 'on'
    then:
    - action: switch.turn_off
      metadata: {}
      data: {}
      target:
        device_id: 3d088840b274c5366c61b3417ba582cc
  mode: single
- id: '1708309195903'
  alias: GitHub Daily Backup
  description: Backup Home Assistant configuration folder
  trigger:
  - platform: time
    at: 02:00:00
  condition: []
  action:
  - service: shell_command.backup
    data: {}
    response_variable: backup_response
  - if:
    - condition: template
      value_template: '{{ backup_response[''returncode''] == 0 }}'
    then:
    - service: notify.notify
      data:
        title: ✅ Backup successful
        message: Github Daily Backup Completed
    else:
    - service: notify.notify
      data:
        title: ❌ Backup failed
        message: '{{ backup_response[''stderr''] }}'
  mode: single
- id: '1709586544091'
  alias: 'Turn ON voice notifications '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.voice_notifications
    from: 'on'
    to: 'off'
  condition: []
  action:
  - delay:
      hours: 4
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.voice_notifications
  mode: single
- id: '1710282519929'
  alias: Speaker Volume Adjust
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_number.speaker_volume
  condition: []
  action:
  - service: media_player.volume_set
    target:
      entity_id:
      - media_player.speakers_group
      device_id: []
      area_id: []
    data:
      volume_level: '{{ states(''input_number.speaker_volume'')}}'
  mode: single
- id: '1710511790171'
  alias: Office Speaker - Volume adjust
  description: ''
  triggers:
  - at: 08:00:00
    id: home
    trigger: time
  - at: '10:00:00'
    id: home
    trigger: time
  conditions:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  actions:
  - target:
      device_id:
      - 084cd82182dbf7573b15b17ee4f4bfd7
      area_id: []
    data:
      volume_level: 0
    action: media_player.volume_set
  mode: single
- id: '1711758261995'
  alias: Aquarium
  description: ''
  triggers:
  - at: 07:02:00
    trigger: time
  - at: '10:03:00'
    trigger: time
  - at: '18:04:00'
    trigger: time
  - at: '21:02:00'
    trigger: time
  conditions: []
  actions:
  - if:
    - condition: device
      type: is_off
      device_id: df4cf792d8865cb18aa9400b9edc7bb3
      entity_id: cd3684ef5ee45d56c934b517b3cbbcf8
      domain: switch
    then:
    - type: turn_on
      device_id: df4cf792d8865cb18aa9400b9edc7bb3
      entity_id: cd3684ef5ee45d56c934b517b3cbbcf8
      domain: switch
    else:
    - type: turn_off
      device_id: df4cf792d8865cb18aa9400b9edc7bb3
      entity_id: cd3684ef5ee45d56c934b517b3cbbcf8
      domain: switch
  mode: single
- id: '1720321855417'
  alias: Alarmo Keypad Sync (San - 01)
  description: ''
  use_blueprint:
    path: zigbee2mqtt-san-keypad-blueprint.yaml
    input:
      state_topic: zigbee2mqtt/Keypad01
      set_topic: zigbee2mqtt/Keypad01/set
      entity: alarm_control_panel.securityalarm3100
- id: '1720322051365'
  alias: Alarmo Keypad Sync (San - 02)
  description: ''
  use_blueprint:
    path: zigbee2mqtt-san-keypad-blueprint.yaml
    input:
      state_topic: zigbee2mqtt/Keypad02
      set_topic: zigbee2mqtt/Keypad02/set
      entity: alarm_control_panel.securityalarm3100
- id: '1721619572709'
  alias: 'New Doors Left Open '
  description: ''
  triggers:
  - minutes: /30
    trigger: time_pattern
  conditions:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.voice_notifications
      state: 'on'
    - condition: state
      entity_id: alarm_control_panel.securityalarm3100
      state: disarmed
      enabled: true
    - condition: state
      entity_id: binary_sensor.door_sensor_group
      state: 'on'
  actions:
  - metadata: {}
    data: {}
    action: script.door_open_script
  mode: single
- id: '1721877086383'
  alias: Nightly Alarm ON
  description: ''
  triggers:
  - at: '21:30:00'
    trigger: time
  - at: '22:00:00'
    trigger: time
  - at: '23:00:00'
    trigger: time
  - at: '23:30:00'
    trigger: time
  conditions:
  - condition: state
    entity_id: alarm_control_panel.securityalarm3100
    state: disarmed
  actions:
  - metadata: {}
    data: {}
    target:
      entity_id: alarm_control_panel.securityalarm3100
    action: alarm_control_panel.alarm_arm_night
  mode: single
- id: '1723660828224'
  alias: Water Flow Notifications
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /12
  condition:
  - condition: state
    entity_id: input_boolean.voice_notifications
    state: 'on'
  - condition: numeric_state
    entity_id: sensor.flume_sensor_3200_60_minutes
    above: 50
  action:
  - target:
      entity_id: media_player.speakers_group
    data:
      media_content_id: media-source://tts/reversotts?message="Increase in water flow
        detected &language=Laura-US-English
      media_content_type: provider
    metadata:
      title: Water Flow - Message
      thumbnail: https://brands.home-assistant.io/_/tts/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/reversotts?message=SpeechNotifications&language=Laura-US-English
    action: media_player.play_media
  mode: single
- id: '1749756464834'
  alias: Trash Reminder Notification
  description: ''
  triggers:
  - at: '20:00:00'
    trigger: time
  conditions:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - thu
  actions:
  - action: script.trashreminder
    metadata: {}
    data: {}
  mode: single
- id: '1752292419309'
  alias: HVAC Cycle Temperature
  description: ''
  use_blueprint:
    path: github.com/hvac_cycle_temp.yaml
    input:
      climate_controller:
        entity_id: climate.ecobeethermostat
      base_temp: 85
      max_temp: 90
      min_temp: 68
      noon_temp: 78
      midnight_temp: 73
      time_offset: 2
      alarm_controller:
        entity_id: alarm_control_panel.securityalarm3100
      default_base_temp: 84
      default_max_temp: 90
      default_min_temp: 68
      default_noon_temp: 78
      default_midnight_temp: 73
      away_base_temp: 90
      away_max_temp: 95
      away_min_temp: 63
      away_noon_temp: 90
      away_midnight_temp: 90
      away_temp: 85
      energy_controller:
        entity_id: input_boolean.energy_saver
