"""Constants for the Reverso text-to-speech integration."""

from dataclasses import dataclass

DOMAIN = "reversotts"
CONF_PITCH = "pitch"
CONF_BITRATE = "bitrate"
DEFAULT_LANG = "Sharon-US-English"
DEFAULT_PITCH = "100"
DEFAULT_BITRATE = "128"
SUPPORT_OPTIONS = ["pitch", "bitrate"]

SUPPORT_LANGUAGES = {
    "Leila-Arabic": "Arabic - Leila",
    "Mehdi-Arabic": "Arabic - Mehdi",
    "Nizar-Arabic": "Arabic - Nizar",
    "Salma-Arabic": "Arabic - Salma",
    "Laia-Catalan": "Catalan - Laia",
    "Lulu-Mandarin-Chinese": "Chinese (Mandarin) - Lulu",
    "Eliska-Czech": "Czech - Eliska",
    "Mette-Danish": "Danish - Mette",
    "Rasmus-Danish": "Danish - Rasmus",
    "Daan-Dutch": "Dutch - Daan",
    "Femke-Dutch": "Dutch - Femke",
    "Jasmijn-Dutch": "Dutch - Jasmijn",
    "Max-Dutch": "Dutch - Max",
    "Jeroen-Belgian-Dutch": "Dutch (BE) - Jeroen",
    "Sofie-Belgian-Dutch": "Dutch (BE) - Sofie",
    "Zoe-Belgian-Dutch": "Dutch (BE) - Zoe",
    "Lisa-Australian-English": "English (AU) - Lisa",
    "Tyler-Australian-English": "English (AU) - Tyler",
    "Graham-British": "English (GB) - Graham",
    "Lucy-British": "English (GB) - Lucy",
    "Peter-British": "English (GB) - Peter",
    "QueenElizabeth-British": "English (GB) - Queen Elisabeth",
    "Rachel-British": "English (GB) - Rachel",
    "Deepa-Indian-English": "English (IN) - Deepa",
    "Heather-US-English": "English (US) - Heather",
    "Karen-US-English": "English (US) - Karen",
    "Kenny-US-English": "English (US) - Kenny",
    "Laura-US-English": "English (US) - Laura",
    "Micah-US-English": "English (US) - Micah",
    "Nelly-US-English": "English (US) - Nelly",
    "Rod-US-English": "English (US) - Rod",
    "Ryan-US-English": "English (US) - Ryan",
    "Saul-US-English": "English (US) - Saul",
    "Sharon-US-English": "English (US) - Sharon",
    "Tracy-US-English": "English (US) - Tracy",
    "Will-US-English": "English (US) - Will",
    "Sanna-Finnish": "Finnish - Sanna",
    "Alice-French": "French - Alice",
    "Anais-French": "French - Anais",
    "Antoine-French": "French - Antoine",
    "Bruno-French": "French - Bruno",
    "Claire-French": "French - Claire",
    "Julie-French": "French - Julie",
    "Manon-French": "French - Manon",
    "Margaux-French": "French - Margaux",
    "Alice-BE-Belgian-French": "French (BE) - Alice",
    "Anais-BE-Belgian-French": "French (BE) - Anais",
    "Antoine-BE-Belgian-French": "French (BE) - Antoine",
    "Bruno-BE-Belgian-French": "French (BE) - Bruno",
    "Claire-BE-Belgian-French": "French (BE) - Claire",
    "Julie-BE-Belgian-French": "French (BE) - Julie",
    "Justine-Belgian-French": "French (BE) - Justine",
    "Manon-BE-Belgian-French": "French (BE) - Manon",
    "Margaux-BE-Belgian-French": "French (BE) - Margaux",
    "Louise-Canadian-French": "French (CA) - Louise",
    "Andreas-German": "German - Andreas",
    "Claudia-German": "German - Claudia",
    "Julia-German": "German - Julia",
    "Klaus-German": "German - Klaus",
    "Sarah-German": "German - Sarah",
    "Dimitris-Greek": "Greek - Dimitris",
    "he-IL-Asaf-Hebrew": "Hebrew - Asaf",
    "Chiara-Italian": "Italian - Chiara",
    "Fabiana-Italian": "Italian - Fabiana",
    "Vittorio-Italian": "Italian - Vittorio",
    "Sakura-Japanese": "Japanese - Sakura",
    "Minji-Korean": "Korean - Minji",
    "Bente-Norwegian": "Norwegian - Bente",
    "Kari-Norwegian": "Norwegian - Kari",
    "Olav-Norwegian": "Norwegian - Olav",
    "Celia-Portuguese": "Portuguese - Celia",
    "Marcia-Brazilian": "Portuguese (BR) - Marcia",
    "Ania-Polish": "Polish - Ania",
    "Monika-Polish": "Polish - Monika",
    "ro-RO-Andrei-Romanian": "Romanian - Andrei",
    "Alyona-Russian": "Russian - Alyona",
    "Antonio-Spanish": "Spanish - Antonio",
    "Ines-Spanish": "Spanish - Ines",
    "Maria-Spanish": "Spanish - Maria",
    "Rodrigo-US-Spanish": "Spanish (US) - Rodrigo",
    "Rosa-US-Spanish": "Spanish (US) - Rosa",
    "Elin-Swedish": "Swedish - Elin",
    "Emil-Swedish": "Swedish - Emil",
    "Emma-Swedish": "Swedish - Emma",
    "Erik-Swedish": "Swedish - Erik",
    "Samuel-Finland-Swedish": "Swedish (FI) - Samuel",
    "Kal-Gothenburg-Swedish": "Swedish (Gothenburg) - Kal",
    "Mia-Scanian": "Swedish (Scanian) - Mia",
    "Ipek-Turkish": "Turkish - Ipek",
}