homeassistant:
  enabled: true
mqtt:
  server: mqtt://192.168.1.50:1883
  user: mqtt_user
  password: yhfgtTHSUS7494
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyUSB0
frontend:
  enabled: true
  port: 8099
advanced: {}
device_options: {}
devices:
  '0xa4c1389679f54d58':
    friendly_name: ZPlug01
  '0xa4c1384a58a142f5':
    friendly_name: ZPlug02
  '0xa4c13878b325acca':
    friendly_name: Laundry_Entrance_Door
    description: Laundry Entrance Door
  '0xa4c138cb15addd8a':
    friendly_name: GarageDoor01
    description: Garage Door
  '0xa4c1382c7dfb1c13':
    friendly_name: Backyard_Door
  '0xa4c1381c891f30ef':
    friendly_name: Main_door
    description: Main Door
  '0xa4c138113fb19080':
    friendly_name: GarageDoor02
  '0xa4c138e0bcb360cc':
    friendly_name: Bedroom_Temp_Sensor
  '0xa4c1384318be8deb':
    friendly_name: Living_Room_Temp_Sensor
  '0xa4c138dbb692ffe1':
    friendly_name: Basement_Temp_Sensor
  '0xa4c138e48b80b383':
    friendly_name: Basement Water Detector
  '0xa4c138beedc1e652':
    friendly_name: Motion Sensor Garage
  '0x000d6f000f5e867b':
    friendly_name: Keypad01
  '0x000d6f001415d557':
    friendly_name: Keypad02
  '0xa4c13816e64d4782':
    friendly_name: Master Bathroom Water Leak Sensor
  '0xa4c13801c72daed8':
    friendly_name: Basement Bathroom Water Leak Sensor
  '0xa4c1385745e35a81':
    friendly_name: Hall Bathroom water leak sensor
  '0xa4c13865385bd935':
    friendly_name: Kitchen water leak sensor
  '0xa4c1382108d38428':
    friendly_name: 'Laundry Water Leak sensor '
  '0xa4c138dbe7413406':
    friendly_name: Common bathroom Water leak sensor
  '0xa4c13806bd3ed514':
    friendly_name: Light Sensor Hall
  '0xbc026efffe0dbb6e':
    friendly_name: ZigbeeExtenderAeotec
  '0x282c02bfffeeeaf2':
    friendly_name: Garage tilt sensor one
  '0x282c02bfffebb06e':
    friendly_name: Garage tilt senor two
  '0xa4c138442284df72':
    friendly_name: '0xa4c138442284df72'
  '0xa4c138b9ebec3506':
    friendly_name: '0xa4c138b9ebec3506'
blocklist:
  - '0x38398ffffe83cfd9'
  - '0xa4c1381796d65b2f'
version: 4
